name: Clippy (SARIF)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "31 12 * * 3"

jobs:
  rust-clippy-analyze:
    name: Run rust-clippy analyzing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # v1.96.1
        with:
          toolchain: stable
          components: clippy

      - uses: cargo-bins/cargo-binstall@732870f031d2fb36309d0deaf36abcc704a7be65
        with:
          version: "1.20.0"

      - name: Install clippy-sarif and sarif-fmt
        run: cargo binstall --no-confirm clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run: cargo clippy --all-features --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
